// <auto-generated />
using System;
using InventoryManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Perifericos",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monitores",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accesorios",
                            Status = "Activo"
                        });
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "USD",
                            Name = "Dolar estadounidense",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 2,
                            Code = "VES",
                            Name = "Bolivar",
                            Status = "Activo"
                        });
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("UsdToVesRate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            UpdatedAtUtc = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsdToVesRate = 572.6800m
                        });
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("00000000000000000000");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("USD");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitOfMeasureId");

                    b.HasIndex("Stock", "MinimumStock");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "10000000000000000001",
                            CategoryId = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Teclado con switch blue",
                            MinimumStock = 10,
                            Name = "Teclado mecanico",
                            PurchasePrice = 52.00m,
                            SalePrice = 75.50m,
                            Status = "Activo",
                            Stock = 4,
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "10000000000000000002",
                            CategoryId = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Panel IPS Full HD",
                            MinimumStock = 5,
                            Name = "Monitor 24 pulgadas",
                            PurchasePrice = 140.00m,
                            SalePrice = 189.99m,
                            Status = "Activo",
                            Stock = 2,
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "10000000000000000003",
                            CategoryId = 3,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Mouse ergonomico",
                            MinimumStock = 8,
                            Name = "Mouse inalambrico",
                            PurchasePrice = 15.75m,
                            SalePrice = 24.90m,
                            Status = "Activo",
                            Stock = 15,
                            UnitOfMeasureId = 1
                        });
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Operator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Auditor"
                        });
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UnitsOfMeasure", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "UND",
                            Name = "Unidad",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 2,
                            Code = "KGR",
                            Name = "Kilogramo",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 3,
                            Code = "GRM",
                            Name = "Gramo",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 4,
                            Code = "LTR",
                            Name = "Litro",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 5,
                            Code = "MLT",
                            Name = "Mililitro",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 6,
                            Code = "CAJ",
                            Name = "Caja",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 7,
                            Code = "PAQ",
                            Name = "Paquete",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 8,
                            Code = "DOC",
                            Name = "Docena",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 9,
                            Code = "PAR",
                            Name = "Par",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 10,
                            Code = "MTR",
                            Name = "Metro",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 11,
                            Code = "CMT",
                            Name = "Centimetro",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 12,
                            Code = "MMT",
                            Name = "Milimetro",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 13,
                            Code = "MT2",
                            Name = "Metro cuadrado",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 14,
                            Code = "MT3",
                            Name = "Metro cubico",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 15,
                            Code = "BOT",
                            Name = "Botella",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 16,
                            Code = "LAT",
                            Name = "Lata",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 17,
                            Code = "ROL",
                            Name = "Rollo",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 18,
                            Code = "SAC",
                            Name = "Saco",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 19,
                            Code = "GAL",
                            Name = "Galon",
                            Status = "Activo"
                        },
                        new
                        {
                            Id = 20,
                            Code = "TON",
                            Name = "Tonelada",
                            Status = "Activo"
                        });
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@mail.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "PBKDF2$SHA1$100000$vV1m6V5tzeMRliH/rB450w==$JlDCqiKUqMI+aNNl1IU3ehFsAS5DH3JDEy61lcPKKkw=",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "operator@mail.com",
                            FullName = "Warehouse Operator",
                            IsActive = true,
                            PasswordHash = "PBKDF2$SHA1$100000$7iHVnSCEfS0wYo3XuDAAgQ==$D+Jvtm+j7k2tygJNaXhYUatMAq5M1aOr29vydHMzlNk=",
                            Username = "operator"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "auditor@mail.com",
                            FullName = "Inventory Auditor",
                            IsActive = true,
                            PasswordHash = "PBKDF2$SHA1$100000$ol6gFD9h7qxAfvgFtGBbTA==$4cR8MwnUTfTrQcJTFIFJHBZE8S91xPtaob3eZ3A6OU4=",
                            Username = "auditor"
                        });
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Product", b =>
                {
                    b.HasOne("InventoryManagement.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryManagement.Domain.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("Products")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("InventoryManagement.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagement.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
